### ISSUE TITLE
change entity ID format for files

### ISSUE THREAD

**Issue by majewsky** [holocm/holo#2]
- before: `holo apply /etc/sudoers`
- after: `holo apply file:/etc/sudoers`

The rationale is to use plain path arguments to apply/diff/scan to select entities based on their resource file (e.g. `holo apply /usr/share/holo/users-groups/01-example.toml`). Since entity IDs are part of the public interface, this change needs to be done before 1.0.

**Comment by mro** [comment]
just a thought: consider valid URLs, e.g. `file:///etc/sudoers`

**Comment by majewsky** [comment]
@mro I've been thinking about this, but I'm skeptical. If I make entity IDs look like URIs in this one plugin, it might create the impression that they always are URIs, which clearly does not hold for other plugins (e.g. `group:sudo` or `script:example.sh`).

**Comment by mro** [comment]
indeed. And to me the `:///` looks ridiculous. But it's worth thinking about it. Maybe the `group:sudo` could conform to [URN](https://de.wikipedia.org/w/index.php?title=Uniform_Resource_Identifier&oldid=145733256#Unterarten). Using an existing standard often turned out to be superior to inventing my own in the (my) past.

**Comment by majewsky** [comment]
I agree in principle. Using existing standards is beneficial where they are applicable, but URIs don't fit the problem quite as nicely as I would like them to if I were to use them. The name "URI" implies that you identify a uniform resource, but `group:sudo` is not a uniform resource. There are multiple groups called `sudo` on multiple hosts. You would only get something worthy of the "URI" name when you identify the host as well. For example, if there were a tool to call Holo across the network, it could address the `group:sudo` of host `example.org` as `holo://example.org/entity/group:sudo`.

**Comment by mro** [comment]
maybe URI (be it URL or URN) is a clumsy choice,

But e.g. `urn:isbn:3827370191` and `urn:nbn:de:bvb:12-bsb00004575-4` are valid [URN](https://de.wikipedia.org/wiki/Uniform_Resource_Name)s and so also valid URIs.

So in fact e.g. `urn:group:sudo` or `urn:holo:group:sudo` are valid URNs.
