### ISSUE TITLE
holo shouln't leak the runtime cache directory if it can't lock

### ISSUE THREAD

**Issue by LukeShu** [holocm/holo#20]
If `AquireLockFile()` can't lock `/run/holo.pid`, then calls `os.Exit` without first calling `CleanupRuntimeCache()`, which means that it leaves empty holo-XXXX directories in TMPDIR.

While the simple fix is trivial (insert a call to `CleanupRuntimeCache()`), since the runtime cache is set up in `init()`, and always needs to be cleaned up before exiting, perhaps `CleanupRuntimeCache` should be replaced with

    func Exit(code int) {
    	_ = os.RemoveAll(cachePath) // fail silently
     	os.Exit(code)
    }

And that function be used instead of `os.Exit()` (obviously with the exception of the call to os.Exit in `runtime.go:init()`).

**Comment by LukeShu** [comment]
Oh, I missed it, but this also happens whenever `main()` `return`s; every time main() returns, it should either call CleanupRuntimeCache, or the call to return be replaced with impl.Exit, as I suggested.

**Comment by majewsky** [comment]
@LukeShu I fixed this, but in a different way from what you proposed on your branch. I changed the API such that it should not be possible to introduce a new leakage ever again.

**Comment by LukeShu** [comment]
Your fix doesn't work.  `defer`ed statements only run on function return or panic; they won't run if `os.Exit()` is called.

**Comment by majewsky** [comment]
Urgh... Well then I'll take another shot tomorrow or so.
