### ISSUE TITLE
Shouldn't holo-files only delete a `.pacsave` file if it matches the file in `${HOLO_STATE_DIR}/provisioned`?

### ISSUE THREAD

**Issue by LukeShu** [holocm/holo#21]
(DPKG and RPM have no equivalent of `.pacsave`, as called out in their AdditionalCleanupTargets implementations).

When Pacman leaves behind a `.pacsave` file, it's because the package removed the file, but the file had been modified from the package-provided version. When holo-files sees a .pacsave file for a file that has been removed in holo, it goes ahead and deletes it, because it is ["most likely a backup of our [holo-files] custom configuration"](https://github.com/holocm/holo/blob/a3d037bba7fe509ef7cd414c6ee201cf2e2636d5/src/holo-files/impl/orphans.go#L57).  However, it is also possible that the user (or another process) manually modified the file too, after holo-files did. With normal (non-orphan) apply operations, holo-files first verifies that no such external modifications have taken place (by comparing the file to the copy made in `${HOLO_STATE_DIR}/provisioned`), to avoid stomping over user changes.  Shouldn't it do the same thing for orphan apply operations?

**Comment by majewsky** [comment]
The scrubbing should use the same logic (or at least share a lot more logic) for new/orig/save files as the normal apply operation, which would lead to it detecting manual edits and requiring `--force`.

I was already sort of aware of the issue some time ago, but didn't come back to it yet, probably because I don't use that particular branch all that often.

**Comment by LukeShu** [comment]
(I'd written .pacorig in the original report, when I (hopefully obviously) meant .pacsave.  Pacman stopped creating .pacorig files with version 5.0.0)

I'd thought about it unconditionally deleting the `.pacsave` file if `--force` is given, and I'm not sure it's ever the right thing to delete save files that don't match the `HOLO_STATE_DIR/provisioned` version; even if `--force` is given.

(When thinking about this, I found it helpful to enumerate all possible cases: https://github.com/LukeShu/holo/blob/82e32a3adf0ed81cd2af459a22b9b2dccaf91838/src/holocm.org/plugins/filesplugin/plugin.go#L49)

I think of `--force` as "use whatever force necessary to put the system in the desired state."  Applying an orphaned file with the "delete" strategy, the "desired state" is simply having FILE not exist.  The fact that FILE.pacsave exists isn't contradictory to that.  However, it is a "mess"; and since the mess is (probably) caused by holo, holo should be courteous and clean it up.  But if the mess wasn't caused by holo, I don't think that holo should get involved. If the user doesn't want the the .pacsave to exist, they should pass `--nosave` to pacman (although, it seems pacman only allows the `--nosave` flag on `-R` operations, even though `-U` and `-S` may also produce `.pacsave` files).

**Comment by LukeShu** [comment]
For completeness: If a `.pacsave` file already exists, pacman starts adding `.N` suffixes (eg `nginx.conf.pacsave.1`).  `AdditionalCleanupTargets()` should probably scan for those too.

**Comment by majewsky** [comment]
@lukeshu I believe this is done, right?

**Comment by LukeShu** [comment]
Oh, yes. It was fixed in #29 .
