### ISSUE TITLE
holo-files: Doesn't require `--force` when first provisioning a file if there's a `.pacnew`

### ISSUE THREAD

**Issue by LukeShu** [holocm/holo#40]
Holo does not handle this situation correctly:

 - Let's say a user modifies `foo.conf`.
 - Then the default changes, and they end up with a `foo.conf.pacnew`
 - So then the user "I don't want to have to deal with merging the changes every time, I'll write a hologram (with a holoscript in it)!", and does so.
 - The user installs the hologram.

There are a couple of things that go wrong here.

First, because it accidentally [effectively sets `base.Path = current.Path`](https://github.com/holocm/holo/blob/b3fa38cfbc749768c83cc0b761a018a8c0c6f4c2/cmd/holo-files/internal/impl/entity_apply_nonorphan.go#L92) because of a copy/paste-type error that is my fault, when it copies `newBase` to `base.Path`, it
 1. overwrites the user's `/etc/foo.conf` with the stock `.pacnew`, without `--force` or anything. BAD.
 2. leaves the user's modified version at `/usr/share/holo/files/base/etc/foo.conf`, which will cause funny results if they change their holoscript before upstream changes the default file.

(the `newBase` handling is the only codepath that uses `base.Path` after the place where it is set incorrectly)

Second, the check that decides if `--force` is needed looks at `/usr/share/holo/files/provisioned/etc/foo.conf` to compare the output of the holoscript with.  But, because Holo's never provisioned `foo.conf` before, that file doesn't exist, and it assumes that `current.EqualTo(base)` (which would be true if we didn't have the `.pacnew`), and that `--force` isn't needed.  This means that even if we fix the first bug, it will *still* overwrite the user's changes without `--force`.

(the only time that the assumption `current.EqualTo(base)` is wrong is when the `newBase` handling bit triggered)

This is the set of bugs fixed by #38 .  It's funny that I found the bug by reading the source, and not in any of my use of holo; but then have already been bitten by it several times since filing the pull request.

**Comment by majewsky** [comment]
So this can be closed now?
