### ISSUE TITLE
ridiculous binary sizes

### ISSUE THREAD

**Issue by majewsky** [holocm/holo#8]
The comfort of [Go](https://golang.org) comes at the cost of [comparatively huge binary sizes](https://github.com/golang/go/issues/6853), which can be a strong argument against Holo e.g. on embedded systems. Can we do better?

Note that, with the new plugin system, parts of Holo can be rewritten in more suitable languages, as has happened with the run-scripts plugin which is now just a simple shell script.

(Migrated from holocm/holo-attic#47.)

**Comment by atweiden** [comment]
here's a noteworthy comparison between Nim and Go binary sizes and perf

http://forum.nim-lang.org/t/1311#8211

**Comment by majewsky** [comment]
Go 1.7 seems to be a real improvement in this area:

```
$ ls -l build        
total 3208
-rwxr-xr-x 1 stefan users 1643360 Aug 17 16:57 holo
-rwxr-xr-x 1 stefan users 1631168 Aug 17 16:57 holo-files
drwxr-xr-x 2 stefan users    4096 Jul 14 14:03 man
```

Compare with the binary sizes as compiled with 1.6:

```
$ ls -l build 
total 4620
-rwxr-xr-x 1 stefan users 2365648 Jul 14 14:03 holo
-rwxr-xr-x 1 stefan users 2357328 Jul 14 15:44 holo-files
drwxr-xr-x 2 stefan users    4096 Jul 14 14:03 man
```

**Comment by majewsky** [comment]
@atweiden I've had a closer look at Nim this evening, and got my feet wet on a little example that reads and parses a configuration file (for some other project, not Holo). What follows is more of a blog post about my experience (since I don't currently run an actual blog ATM).

Nim itself feels a lot unlike Go and, interestingly, a lot like C++:
1. Non-orthogonal features. In C++, there are references, which are like pointers, but not quite, so you always have to think about which one to use. In Nim, non-orthogonal features include tuples vs. objects, and sequences vs. openarrays.
2. Feature creep. Just look at the [language manual](http://nim-lang.org/docs/manual.html): generic functions, type classes, 10 calling conventions (10!), garbage collection (not sure if optional or not), inline assembler, operator overloading, exceptions, an effect system. Name any contemporary programming language feature, chances are that Nim has it.

Then there's the documentation. The [language manual](http://nim-lang.org/docs/manual.html) is okay-ish, considering the size of the language. But when I dive into the library reference, the [built-in module "system"](http://nim-lang.org/docs/system.html) is so outlandishly huge and the documentation so badly formatted that it takes a lot of hunting to find what's in this module (and what isn't). Just look at all the duplicate entries in the navigation bar on the left. The system module should definitely have been split into multiple modules for the multiple concerns it covers, possibly with reexports in the actual "system" module to make sure they're all imported by default. Some parts should just be moved out of it, for example the whole file IO business belongs into "os" IMO.

Another thing that concerns me about the standard library is how many duplication is going on in there. There are at least 4 different XML parser AFAICS, and two regular expression libraries, both based on the same backend (pcre). This might be the same confusion that most languages suffer from in their pre-1.0 stabilization phase, but especially then, it's a strong argument not to use the language in production pre-1.0.

The thing that really killed it for me that I was able to produce `SIGSEGV` by accident, without the compiler warning me about it. I think I wrote something along the lines of:

``` nim
type Config = tuple
  someSetting:    string
  anotherSetting: string

proc readConfigFile(path: string): Config =
  var file = open(path)
  defer: file.close()
  # TODO: implement the rest
  var cfg: Config
  return cfg

var cfg = readConfigFile("./example-config")
echo(cfg.someSetting) # this produces a SIGSEGV; probably because the memory backing `cfg` is not initialized
```

In 2016, I expect any new language to warn me about (or outright refuse to compile) code that might access uninitialized memory or do any other unsafe stuff, especially for a program that will run as root.

**Comment by srh** [comment]
Your example doesn't produce SIGSEGV for me.  It prints out the text, "nil".

However, if I write

```
echo(cfg.someSetting[0])
```

it will segfault.  This makes sense because it dereferences a null pointer (in Nim-speak, a nil value).  I would guess that's what you experienced.

Dereferencing a null pointer is not unsafe.  The program cleanly exits.  Compiling that via C is sketchy though, because the C compiler may treat provable null pointer dereferences as undefined behavior.

**Comment by majewsky** [comment]
Ah, sorry. I checked the branch where I committed the half-finished code snippet, and the segv actually occurs where I read the file:

``` nim
var file = open(path)
defer: file.close()
var line: string
while file.readLine(line):
  echo("Read a line: " & line)
```

The stacktrace leads to `readLine`, where `line == nil` is passed and not handled correctly. So from the looks of it, this might just be a bug in the library function that does not check for `nil` arguments correctly. But even then, this is an error that should have been caught by a compiler warning before it even shipped.

**Comment by srh** [comment]
That's not a bug, it's a design decision.  (The right decision.)

**Comment by majewsky** [comment]
There is never "the right design decision". It depends on what you're trying to achieve. My review basically says that Nim is not meeting the requirements that I have in a language. I don't say that Nim is a bad language, it's just a bad language _for me_.

**Comment by atweiden** [comment]
It would be enjoyable to read your experience with Nim turned into a blogpost, and I suspect the Nim community would benefit from your feedback. cc @Araq

**Comment by florianjacob** [comment]
Yes, thanks for testing Nim and writing about it. Now I don't have to do that myself, as I have quite similar requirements. :wink:

**Comment by Araq** [comment]
I don't see how Golang prevents nil errors at compile time, in fact it's famous for doing nothing whatsoever about it... That this fact for you killed Nim in comparison to Golang is completely absurd. Nor do I see how not supporting calling conventions (which stem from the fact that we strive for excellent interop with C on Windows) simplifies a language. Ok, in Golang it's probably done by some "comment misused as a compiler directive" somewhere and not documented. Congrats, Golang stays "simple".

**Comment by majewsky** [comment]
I didn't kill Nim in comparison to Go. The argument is that if I rewrite the thing, then it'd better be in a safer language.

**Comment by LukeShu** [comment]
I was curious if Cgo linking against libc et al. was increasing the size (yes, but only by a couple of kB).

Cutting out Cgo wouldn't be effective in reducing the binary size, but I'm still curious: Is Cgo really necessary?  It's only being pulled in to call setlocale(3), but I'm reasonably certain that setlocale will have no impact on the Go runtime or any forked processes (that is, it has no impact unless making further use of Cgo).

**Comment by majewsky** [comment]
The 2.0 release reduces size considerably by merging all binaries into one, so that the overhead of the Go runtime and stdlib is paid only once. Before upgrade:

```
$ pacman -Qi holo{,-{run-scripts,ssh-keys,users-groups}} | grep -E '^Name|^Installed'
Name            : holo
Installed Size  : 3,29 MiB
Name            : holo-run-scripts
Installed Size  : 49,00 KiB
Name            : holo-ssh-keys
Installed Size  : 1641,00 KiB
Name            : holo-users-groups
Installed Size  : 1981,00 KiB
```

After upgrade:

```
Name            : holo
Installed Size  : 2,49 MiB
```

I consider this size reduction sufficient to justify closing this issue, esp. since I'm much less keen on spending time rewriting this than I used to a year ago or so.
